{
 "bad": false,
 "new_version": "9e",
 "new_version_attempts": {
  "2.0.5": 2,
  "9d": 27,
  "9e": 123
 },
 "new_version_errors": {
  "9d": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '9d' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz'\n",
  "9e": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9465733947\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 211, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration\n    return run_migration_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 136, in run_migration_containerized\n    logger.debug(f\"host feedstock dir {feedstock_dir}: {os.listdir(feedstock_dir)}\")\n                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/cf-scripts/cf-scripts/cf-graph/libjpeg-turbo-feedstock'\n"
 }
}