{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": {
  "exception": "Error running migrate-feedstock in container - error VersionMigrationError(\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\\n\\nPlease check the URLs in your recipe with version '1.0.1' to make sure they exist!\\n\\nWe also found the following errors:\\n\\n - recipe did not appear to change even though the bot said it should have\\n\") raised:\ncmd: ['docker',\n 'run',\n '-e',\n 'CF_TICK_IN_CONTAINER=true',\n '--security-opt=no-new-privileges',\n '--read-only',\n '--cap-drop=all',\n '--mount',\n 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',\n '-m',\n '6000m',\n '--cpus',\n '1',\n '--ulimit',\n 'nofile=1024:1024',\n '--ulimit',\n 'nproc=2048:2048',\n '--rm',\n '-i',\n '--mount',\n 'type=bind,source=/tmp/tmpumdm2fpc,destination=/cf_tick_dir',\n 'ghcr.io/regro/conda-forge-tick:master',\n '/opt/conda/envs/cf-scripts/bin/python',\n '-u',\n '/opt/autotick-bot/docker/run_bot_task.py',\n 'migrate-feedstock',\n '--feedstock-name',\n 'enterprise_outliers',\n '--default-branch',\n 'main',\n '--existing-feedstock-node-attrs',\n '-',\n '--kwargs',\n '{\\n \"hash_type\": \"sha256\"\\n}',\n '--log-level',\n 'info']\nstdout: {'data': None,\n 'default_branch': 'main',\n 'error': 'VersionMigrationError(\"The recipe did not change in the version '\n          'migration, a URL did not hash, or there is jinja2 syntax the bot '\n          'cannot handle!\\\\n\\\\nPlease check the URLs in your recipe with '\n          \"version '1.0.1' to make sure they exist!\\\\n\\\\nWe also found the \"\n          'following errors:\\\\n\\\\n - recipe did not appear to change even '\n          'though the bot said it should have\\\\n\")',\n 'feedstock_name': 'enterprise_outliers',\n 'input_kwargs': '{\\n \"hash_type\": \"sha256\"\\n}',\n 'traceback': 'Traceback (most recent call last):\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 120, in '\n              '_run_bot_task\\n'\n              '    data = func(attrs=attrs, **kwargs)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 308, in '\n              '_migrate_feedstock\\n'\n              '    data = run_migration_local(\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line '\n              '241, in run_migration_local\\n'\n              '    data[\"migrate_return_value\"] = migrator.migrate(\\n'\n              '                                   ^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line '\n              '215, in migrate\\n'\n              '    raise VersionMigrationError(\\n'\n              'conda_forge_tick.migrators.version.VersionMigrationError: The '\n              'recipe did not change in the version migration, a URL did not '\n              'hash, or there is jinja2 syntax the bot cannot handle!\\n'\n              '\\n'\n              \"Please check the URLs in your recipe with version '1.0.1' to \"\n              'make sure they exist!\\n'\n              '\\n'\n              'We also found the following errors:\\n'\n              '\\n'\n              ' - recipe did not appear to change even though the bot said it '\n              'should have\\n'\n              '\\n'}",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 572, in _run_migrator_on_feedstock_branch",
   "    migrator_uid, pr_json = run(",
   "                            ^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 216, in run",
   "    migration_run_data = run_migration(",
   "                         ^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration",
   "    return run_migration_containerized(",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 157, in run_migration_containerized",
   "    data = run_container_task(",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 249, in run_container_task",
   "    raise RuntimeError(",
   "RuntimeError: Error running migrate-feedstock in container - error VersionMigrationError(\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\\n\\nPlease check the URLs in your recipe with version '1.0.1' to make sure they exist!\\n\\nWe also found the following errors:\\n\\n - recipe did not appear to change even though the bot said it should have\\n\") raised:",
   "cmd: ['docker',",
   " 'run',",
   " '-e',",
   " 'CF_TICK_IN_CONTAINER=true',",
   " '--security-opt=no-new-privileges',",
   " '--read-only',",
   " '--cap-drop=all',",
   " '--mount',",
   " 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',",
   " '-m',",
   " '6000m',",
   " '--cpus',",
   " '1',",
   " '--ulimit',",
   " 'nofile=1024:1024',",
   " '--ulimit',",
   " 'nproc=2048:2048',",
   " '--rm',",
   " '-i',",
   " '--mount',",
   " 'type=bind,source=/tmp/tmpumdm2fpc,destination=/cf_tick_dir',",
   " 'ghcr.io/regro/conda-forge-tick:master',",
   " '/opt/conda/envs/cf-scripts/bin/python',",
   " '-u',",
   " '/opt/autotick-bot/docker/run_bot_task.py',",
   " 'migrate-feedstock',",
   " '--feedstock-name',",
   " 'enterprise_outliers',",
   " '--default-branch',",
   " 'main',",
   " '--existing-feedstock-node-attrs',",
   " '-',",
   " '--kwargs',",
   " '{\\n \"hash_type\": \"sha256\"\\n}',",
   " '--log-level',",
   " 'info']",
   "stdout: {'data': None,",
   " 'default_branch': 'main',",
   " 'error': 'VersionMigrationError(\"The recipe did not change in the version '",
   "          'migration, a URL did not hash, or there is jinja2 syntax the bot '",
   "          'cannot handle!\\\\n\\\\nPlease check the URLs in your recipe with '",
   "          \"version '1.0.1' to make sure they exist!\\\\n\\\\nWe also found the \"",
   "          'following errors:\\\\n\\\\n - recipe did not appear to change even '",
   "          'though the bot said it should have\\\\n\")',",
   " 'feedstock_name': 'enterprise_outliers',",
   " 'input_kwargs': '{\\n \"hash_type\": \"sha256\"\\n}',",
   " 'traceback': 'Traceback (most recent call last):\\n'",
   "              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 120, in '",
   "              '_run_bot_task\\n'",
   "              '    data = func(attrs=attrs, **kwargs)\\n'",
   "              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'",
   "              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 308, in '",
   "              '_migrate_feedstock\\n'",
   "              '    data = run_migration_local(\\n'",
   "              '           ^^^^^^^^^^^^^^^^^^^^\\n'",
   "              '  File '",
   "              '\"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line '",
   "              '241, in run_migration_local\\n'",
   "              '    data[\"migrate_return_value\"] = migrator.migrate(\\n'",
   "              '                                   ^^^^^^^^^^^^^^^^^\\n'",
   "              '  File '",
   "              '\"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line '",
   "              '215, in migrate\\n'",
   "              '    raise VersionMigrationError(\\n'",
   "              'conda_forge_tick.migrators.version.VersionMigrationError: The '",
   "              'recipe did not change in the version migration, a URL did not '",
   "              'hash, or there is jinja2 syntax the bot cannot handle!\\n'",
   "              '\\n'",
   "              \"Please check the URLs in your recipe with version '1.0.1' to \"",
   "              'make sure they exist!\\n'",
   "              '\\n'",
   "              'We also found the following errors:\\n'",
   "              '\\n'",
   "              ' - recipe did not appear to change even though the bot said it '",
   "              'should have\\n'",
   "              '\\n'}",
   ""
  ]
 },
 "pinning_version": "2022.11.06.17.50.32",
 "pre_pr_migrator_attempts": {
  "python312": 37
 },
 "pre_pr_migrator_status": {
  "python312": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9346175159'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 enterprise-pulsar >=3.1.0  is installable with the potential options\n\u2502  \u251C\u2500 enterprise-pulsar [3.1.0|3.2.0|3.2.1] would require\n\u2502  \u2502  \u251C\u2500 ephem >=3.7.6.0  with the potential options\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|3.7.7.1] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem 3.7.6.0 would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem 3.7.6.0 would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python 3.6* , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|...|4.1] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.6,<3.7.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|...|4.1.3] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.7,<3.8.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.7.0|3.7.7.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.8,<3.9.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.7.0|3.7.7.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.9,<3.10.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1|4.1.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.10,<3.11.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1|4.1.1|4.1.3] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.7 *_pypy37_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.7.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.2|4.1.3|4.1.4|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.11,<3.12.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.3|4.1.4] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.8 *_pypy38_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.8.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.3|4.1.4|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u251C\u2500 pypy3.9 >=7.3.13 , which requires\n\u2502  \u2502  \u2502  \u2502  \u2502  \u2514\u2500 python 3.9.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.9 *_pypy39_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.9.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u2514\u2500 ephem 4.1.5 would require\n\u2502  \u2502  \u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which requires\n\u2502  \u2502  \u2502        \u2514\u2500 python 3.12.* *_cpython, which can be installed;\n\u2502  \u2502  \u2514\u2500 pint-pulsar >=0.8.2  but there are no viable options\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|0.8|0.8.1|0.8.2] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.6.* *_cp36m, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|...|0.8.8] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.8|0.8.1|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.8.4|0.8.5|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 pint-pulsar [0.9.1|0.9.2|...|1.0] would require\n\u2502  \u2502        \u2514\u2500 python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 enterprise-pulsar [3.2.2|3.2.3|3.3.0|3.3.1] would require\n\u2502  \u2502  \u2514\u2500 python >=3.6,<3.10 , which can be installed;\n\u2502  \u2514\u2500 enterprise-pulsar 3.3.2 would require\n\u2502     \u2514\u2500 python >=3.7,<3.11 , which can be installed;\n\u251C\u2500 pint-pulsar, which cannot be installed (as previously explained);\n\u251C\u2500 python >=3.12,<3.13.0a0  is not installable because there are no viable options\n\u2502  \u251C\u2500 python [3.12.0|3.12.1|3.12.2|3.12.3] conflicts with any installable versions previously reported;\n\u2502  \u2514\u2500 python [3.12.0|3.12.1|3.12.2|3.12.3] would require\n\u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2514\u2500 python_abi 3.12.* *_cp312, which can be installed (as previously explained).</pre><pre>osx_64_python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 enterprise-pulsar >=3.1.0  is installable with the potential options\n\u2502  \u251C\u2500 enterprise-pulsar [3.1.0|3.2.0|3.2.1] would require\n\u2502  \u2502  \u251C\u2500 ephem >=3.7.6.0  with the potential options\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|3.7.7.1] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem 3.7.6.0 would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem 3.7.6.0 would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python 3.6* , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|...|4.1] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.6,<3.7.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.6.0|3.7.7.0|...|4.1.3] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.7,<3.8.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.7.0|3.7.7.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.8,<3.9.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [3.7.7.0|3.7.7.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.9,<3.10.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1|4.1.1|...|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.10,<3.11.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1|4.1.1|4.1.3] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.7 *_pypy37_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.7.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.2|4.1.3|4.1.4|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python >=3.11,<3.12.0a0 , which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.3|4.1.4] would require\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.8 *_pypy38_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.8.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u251C\u2500 ephem [4.1.3|4.1.4|4.1.5] would require\n\u2502  \u2502  \u2502  \u2502  \u251C\u2500 pypy3.9 >=7.3.13 , which requires\n\u2502  \u2502  \u2502  \u2502  \u2502  \u2514\u2500 python 3.9.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u2502  \u2514\u2500 python_abi 3.9 *_pypy39_pp73, which requires\n\u2502  \u2502  \u2502  \u2502     \u2514\u2500 python 3.9.* *_73_pypy, which can be installed;\n\u2502  \u2502  \u2502  \u2514\u2500 ephem 4.1.5 would require\n\u2502  \u2502  \u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which requires\n\u2502  \u2502  \u2502        \u2514\u2500 python 3.12.* *_cpython, which can be installed;\n\u2502  \u2502  \u2514\u2500 pint-pulsar >=0.8.2  but there are no viable options\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|0.8|0.8.1|0.8.2] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.6.* *_cp36m, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|...|0.8.8] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.6.3|0.7|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.8|0.8.1|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 pint-pulsar [0.8.4|0.8.5|...|1.0] would require\n\u2502  \u2502     \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 pint-pulsar [0.9.1|0.9.2|...|1.0] would require\n\u2502  \u2502        \u2514\u2500 python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 enterprise-pulsar [3.2.2|3.2.3|3.3.0|3.3.1] would require\n\u2502  \u2502  \u2514\u2500 python >=3.6,<3.10 , which can be installed;\n\u2502  \u2514\u2500 enterprise-pulsar 3.3.2 would require\n\u2502     \u2514\u2500 python >=3.7,<3.11 , which can be installed;\n\u251C\u2500 pint-pulsar, which cannot be installed (as previously explained);\n\u251C\u2500 python >=3.12,<3.13.0a0  is not installable because there are no viable options\n\u2502  \u251C\u2500 python [3.12.0|3.12.1|3.12.2|3.12.3] conflicts with any installable versions previously reported;\n\u2502  \u2514\u2500 python [3.12.0|3.12.1|3.12.2|3.12.3] would require\n\u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2514\u2500 python_abi 3.12.* *_cp312, which can be installed (as previously explained).\n                </pre>\n                </div>\n                </details>"
 },
 "smithy_version": "3.21.3"
}